name: integrador
description: "A new Flutter project."

# Esta línea evita que el paquete se publique accidentalmente en pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# La siguiente define el número de versión y build de tu aplicación.
# Una versión number está compuesta por tres números separados por puntos, como 1.2.43
# seguidos por un número opcional build separado por un +.
# Tanto la versión como el número builder pueden ser sobrescritos en flutter
# build especificando --build-name y --build-number, respectivamente.
# En Android, build-name es usado como versionName mientras que build-number es usado como versionCode.
# Lee más sobre versioning en: https://developer.android.com/studio/publish/versioning
# En iOS, build-name es usado como CFBundleShortVersionString mientras que build-number se usa como CFBundleVersion.
# Lee más sobre versioning en: https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

# Dependencies especifica otros paquetes que tu paquete necesita para funcionar.
# Para automáticamente actualizar tus dependencias de paquetes, puedes ejecutar `flutter pub upgrade --major-versions`.
# Alternativamente, dependencias pueden ser actualizadas manualmente cambiando las versiones aquí, y luego
# ejecutando `flutter pub get` en la consola.
dependencies:
  flutter:
    sdk: flutter
    
  image_picker: ^0.8.4+8
  qr_flutter: ^4.1.0
  cupertino_icons: ^1.0.6
  http: ^0.13.3
  twilio_flutter: ^0.0.9
  shared_preferences: ^2.2.2

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # El "flutter_lints" package a continuación contiene un conjunto de recomendaciones de lints
  # para fomentar buenas prácticas de codificación. El conjunto provisto por el package es
  # activado en el archivo `analysis_options.yaml` que se encuentra en la raíz del proyecto.
  flutter_lints: ^3.0.1

# Para información sobre la parte genérica de este archivo, ver el
# siguiente enlace: https://dart.dev/tools/pub/pubspec

# La siguiente sección es específica para Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Para agregar assets a tu aplicación, agrega una sección assets, como esta:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Una imagen asset puede referir a una o más variaciones de resolución específica de una imagen.
  # Ver: https://flutter.dev/assets-and-images/#resolution-aware

  # Para detalles sobre cómo agregar assets desde package dependencies, ver
  # https://flutter.dev/assets-and-images/#from-packages

  # Para agregar fuentes personalizadas a tu aplicación, agrega una sección de fuentes aquí,
  # en esta sección "flutter". Cada entrada en esta lista debe tener una
  # "family" key con el nombre de la familia de la fuente, y una "fonts" key con una
  # lista que contiene el asset y otros descriptores específicos para la fuente. Por ejemplo:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # Para detalles sobre las fuentes desde packages, ver
  # https://flutter.dev/custom-fonts/#from-packages